import { shellQuote } from '@shared/format'

export type CommandKind = 'trash' | 'reveal' | 'paths' | 'remove'

export const COMMAND_LABEL: Record<CommandKind, string> = {
  trash: 'Move to Trash',
  reveal: 'Reveal in Finder',
  paths: 'Copy paths',
  remove: 'Delete permanently',
}

export const COMMAND_HINT: Record<CommandKind, string> = {
  trash: 'Recoverable from Finder',
  reveal: 'Opens each enclosing folder',
  paths: 'One path per line, unquoted',
  remove: 'No undo',
}

/**
 * Build one command covering every selected path.
 *
 * `mv` and `open` both accept many sources, so the whole selection is a single
 * command to paste — which is the point. `rm -rf` does too, and is deliberately
 * the least convenient thing here: it is never a default and never pre-filled.
 */
export function buildCommand(kind: CommandKind, paths: readonly string[]): string {
  if (paths.length === 0) return ''
  const quoted = paths.map(shellQuote)

  switch (kind) {
    case 'trash':
      return `mv -n ${quoted.join(' ')} ~/.Trash/`
    case 'reveal':
      return `open -R ${quoted.join(' ')}`
    case 'remove':
      return `rm -rf ${quoted.join(' ')}`
    case 'paths':
      return paths.join('\n')
  }
}

/**
 * A reviewable script rather than a one-liner.
 *
 * One `mv` per line means a failure on one item does not take the rest with it,
 * and the diff between "what I selected" and "what will run" is readable line by
 * line. The header records what the selection was worth.
 */
export function buildScript(
  items: ReadonlyArray<{ path: string; size: number }>,
  totalLabel: string,
  ledgerPath = '.scan-cache/deleted.log',
): string {
  const lines = [
    '#!/bin/sh',
    '# Generated by Disk Report. Review before running.',
    `# ${items.length} item(s), ${totalLabel}.`,
    '# Items are moved to the Trash and keep using disk until it is emptied.',
    '#',
    '# Each successful move is appended to the ledger below. The next scan reads',
    '# it first and reports whether each path is really gone — the browser cannot',
    '# write files, so this script is what carries the intent to the scanner.',
    '',
    // No `set -e`: one failed move must not abandon the rest, and each line
    // records itself only if it actually succeeded.
    `LEDGER=${shellQuote(ledgerPath)}`,
    'mkdir -p "$(dirname "$LEDGER")"',
    'STAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)',
    '',
  ]
  for (const item of items) {
    const quoted = shellQuote(item.path)
    lines.push(
      `mv -n ${quoted} ~/.Trash/ && printf '%s\\t%s\\n' "$STAMP" ${quoted} >> "$LEDGER"`,
    )
  }
  lines.push('')
  return lines.join('\n')
}

/**
 * `mv` refuses to move two items with the same basename into one directory —
 * with `-n` the second is skipped silently, which would look like the command
 * worked. Worth saying out loud before it happens.
 */
export function collidingBasenames(paths: readonly string[]): string[] {
  const seen = new Map<string, number>()
  for (const path of paths) {
    const name = path.slice(path.lastIndexOf('/') + 1)
    seen.set(name, (seen.get(name) ?? 0) + 1)
  }
  return [...seen.entries()]
    .filter(([, count]) => count > 1)
    .map(([name]) => name)
    .sort()
}
