// Code generated by tools/gen-go-types.ts. DO NOT EDIT.
//
// Source: shared/schema.ts — the canonical snapshot schema, shared with the SPA.
// Regenerate with `bun run gen:types`.

package schema

// SchemaVersion — Bumped whenever a change makes older snapshots unreadable by the SPA.
const SchemaVersion = 1

// Category — Coarse grouping layered on top of raw extensions. Two hundred extensions is
// an unreadable chart; ten categories is a story.
type Category string

const (
	CategoryVideo     Category = "video"
	CategoryImage     Category = "image"
	CategoryAudio     Category = "audio"
	CategoryArchive   Category = "archive"
	CategoryDiskimage Category = "diskimage"
	CategoryCode      Category = "code"
	CategoryCache     Category = "cache"
	CategoryDocument  Category = "document"
	CategoryBinary    Category = "binary"
	CategoryData      Category = "data"
	CategoryOther     Category = "other"
)

var Categories = []Category{
	CategoryVideo,
	CategoryImage,
	CategoryAudio,
	CategoryArchive,
	CategoryDiskimage,
	CategoryCode,
	CategoryCache,
	CategoryDocument,
	CategoryBinary,
	CategoryData,
	CategoryOther,
}

// NoExtension — Extension used for files that have none (`Makefile`, `.zshrc`, binaries).
const NoExtension = ""

// HistogramBuckets — Size histograms use power-of-two buckets: index `i` counts files whose size
// falls in `[2^i, 2^(i+1))`. Bucket 0 also absorbs zero-byte files. 48 buckets
// reaches 281 TB, comfortably past any single file. Histograms are mergeable,
// which is what lets each worker aggregate locally (see docs/DECISIONS.md).
const HistogramBuckets = 48

type ScanConfig struct {
	// Absolute roots to walk. Defaults to `[$HOME]`.
	Roots []string `json:"roots"`

	// Files at or above this many bytes are reported individually.
	MinFileSize int64 `json:"minFileSize"`

	// Folders whose recursive size is at or above this appear in the tree.
	MinFolderSize int64 `json:"minFolderSize"`

	// Cap on individually reported files per extension.
	TopNPerExtension int64 `json:"topNPerExtension"`

	// Cap on individually reported files overall.
	GlobalTopN int64 `json:"globalTopN"`

	// Worker threads used for the walk.
	WorkerCount int64 `json:"workerCount"`

	// Directory extensions treated as one atomic item (`app`, `photoslibrary`).
	BundleExtensions []string `json:"bundleExtensions"`

	// Multi-segment extensions preserved whole (`tar.gz`).
	CompoundExtensions []string `json:"compoundExtensions"`

	// Extension -> category. Extensions absent here fall back to `other`.
	CategoryMap map[string]Category `json:"categoryMap"`

	// Absolute paths (or path prefixes) skipped entirely.
	ExcludePaths []string `json:"excludePaths"`

	// Symlinks are never followed when false — cycles and double counting.
	FollowSymlinks bool `json:"followSymlinks"`

	// When false the walk stops at any `st_dev` change (mounts, network shares).
	CrossFilesystems bool `json:"crossFilesystems"`

	// Second pass that fingerprints files sharing an exact size, to find
	// byte-identical groups (APFS clones and real duplicates alike).
	DetectDuplicates bool `json:"detectDuplicates"`

	// Only files at or above this size are considered for fingerprinting.
	DuplicateMinSize int64 `json:"duplicateMinSize"`
}

type FileEntry struct {
	// Absolute path.
	Path string `json:"path"`

	// Normalized extension, `''` when the file has none.
	Ext      string   `json:"ext"`
	Category Category `json:"category"`

	// Physical bytes on disk (`blocks * 512`), not logical size.
	Size int64 `json:"size"`

	// stat returns sub-millisecond precision.
	MtimeMs float64 `json:"mtimeMs"`

	// Unreliable on macOS: Spotlight, backups and indexers bump it.
	AtimeMs     float64 `json:"atimeMs"`
	BirthtimeMs float64 `json:"birthtimeMs"`

	// A directory treated as one atomic item (`.app`, `.photoslibrary`).
	IsBundle bool `json:"isBundle"`

	// Lives under iCloud Drive or a CloudStorage provider — may be evicted.
	IsCloud bool `json:"isCloud"`

	// `st_nlink > 1`: the same bytes are reachable from another path.
	IsHardlink bool `json:"isHardlink"`

	// A hardlink whose inode was already counted at another path. Its bytes are
	// excluded from every total, and deleting it alone frees nothing.
	IsDupInode bool  `json:"isDupInode"`
	Nlink      int64 `json:"nlink"`

	// Fingerprint shared by byte-identical files, when duplicate detection ran.
	DuplicateGroup *string `json:"duplicateGroup,omitempty"`

	// How many files carry this fingerprint, including this one.
	DuplicateCopies *int64 `json:"duplicateCopies,omitempty"`

	// True for every copy but the first seen — the redundant ones.
	IsDuplicateCopy *bool `json:"isDuplicateCopy,omitempty"`
}

// DuplicateGroup — A set of byte-identical files.
//
// Two files can be identical for two very different reasons, and `stat` cannot
// tell them apart:
//
// - **APFS clones** share the same blocks. Each copy is billed its full size by
// `stat` and `du`, but deleting one frees nothing; the group really occupies
// `size` bytes, not `size * count`.
// - **Real duplicates** each occupy their own blocks. The group really occupies
// `size * count`, and deleting the extra copies frees `reclaimableBytes`.
//
// Distinguishing them needs APFS-specific introspection (clone IDs), so the
// snapshot reports the group and lets the UI present both readings. When the
// scan total exceeds the volume's used bytes, clones are proven to be present.
type DuplicateGroup struct {
	Fingerprint string `json:"fingerprint"`

	// Size of one copy, in physical bytes.
	Size  int64 `json:"size"`
	Count int64 `json:"count"`

	// `size * (count - 1)` — freed by deleting the extras, if they are real copies.
	ReclaimableBytes int64    `json:"reclaimableBytes"`
	Ext              string   `json:"ext"`
	Category         Category `json:"category"`

	// Capped sample of member paths, biggest-group-first ordering preserved.
	Paths []string `json:"paths"`
}

// RecheckedPath — The verdict on a path the user meant to delete.
//
// The app cannot write files and the scanner cannot read a browser, so the
// bridge is the cleanup script: it appends every path it actually moved to a
// ledger, and the next scan checks those paths **before** walking anything.
type RecheckedPath struct {
	Path string `json:"path"`

	// Recorded when the cleanup script moved it.
	IntendedAt string `json:"intendedAt"`

	// Still on disk at scan time — the deletion did not happen or was undone.
	Present bool `json:"present"`

	// Physical bytes if still present.
	Size int64 `json:"size"`
}

// VolumeInfo — Volume figures from `df`, used to sanity-check the scan against reality.
type VolumeInfo struct {
	Path           string `json:"path"`
	TotalBytes     int64  `json:"totalBytes"`
	UsedBytes      int64  `json:"usedBytes"`
	AvailableBytes int64  `json:"availableBytes"`
}

type FolderNode struct {
	Path string `json:"path"`

	// Basename, for display.
	Name string `json:"name"`

	// Folder plus every descendant. Overlaps ancestors — never sum siblings and parents.
	RecursiveSize int64 `json:"recursiveSize"`

	// Files directly inside this folder only. Safe to sum across a flat list.
	OwnSize      int64 `json:"ownSize"`
	FileCount    int64 `json:"fileCount"`
	OwnFileCount int64 `json:"ownFileCount"`

	// Freshest `mtime` anywhere beneath — the folder's real activity signal.
	MaxMtimeMs float64 `json:"maxMtimeMs"`
	IsCloud    bool    `json:"isCloud"`

	// Bytes held by redundant copies among this folder's own files.
	DuplicateOwnSize int64 `json:"duplicateOwnSize"`

	// Same, across the whole subtree. `recursiveSize` minus this is the floor.
	DuplicateRecursiveSize int64 `json:"duplicateRecursiveSize"`

	// Only children at or above `minFolderSize`.
	Children []FolderNode `json:"children"`

	// Children omitted for being under threshold, and their combined weight.
	TruncatedChildCount int64 `json:"truncatedChildCount"`
	TruncatedSize       int64 `json:"truncatedSize"`
}

type ExtensionStat struct {
	Ext       string   `json:"ext"`
	Category  Category `json:"category"`
	TotalSize int64    `json:"totalSize"`
	FileCount int64    `json:"fileCount"`

	// Rounded: a mean of byte counts is still reported in whole bytes.
	MeanSize int64 `json:"meanSize"`

	// Approximated from the histogram — accurate to a power of two.
	MedianSize int64 `json:"medianSize"`
	P95Size    int64 `json:"p95Size"`
	MaxSize    int64 `json:"maxSize"`

	// Path of the single biggest file with this extension.
	LargestPath string `json:"largestPath"`

	// Bytes held by redundant copies of byte-identical files of this type.
	DuplicateBytes int64   `json:"duplicateBytes"`
	Histogram      []int64 `json:"histogram"`
}

type CategoryStat struct {
	Category  Category `json:"category"`
	TotalSize int64    `json:"totalSize"`
	FileCount int64    `json:"fileCount"`

	// Bytes held by redundant copies within this category.
	DuplicateBytes int64 `json:"duplicateBytes"`

	// Extensions contributing to this category, biggest first.
	Extensions []string `json:"extensions"`
}

type ScanError struct {
	Path string `json:"path"`

	// errno code: `EPERM`, `EACCES`, `ELOOP`, ...
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ScanTotals struct {
	// Physical bytes as the filesystem reports them, after hardlink dedup. This
	// is what `du` and Finder show, and it over-counts APFS clones.
	Bytes int64 `json:"bytes"`
	Files int64 `json:"files"`
	Dirs  int64 `json:"dirs"`

	// Bytes skipped because another path already claimed the inode.
	DedupedBytes int64 `json:"dedupedBytes"`
	DedupedFiles int64 `json:"dedupedFiles"`

	// Bytes under paths that could not be read (always 0 — listed for clarity).
	UnreadablePaths int64 `json:"unreadablePaths"`

	// `bytes` minus every redundant copy: the floor of what is really stored.
	UniqueBytes int64 `json:"uniqueBytes"`

	// Bytes held by redundant copies of byte-identical files.
	DuplicateBytes int64 `json:"duplicateBytes"`
	DuplicateFiles int64 `json:"duplicateFiles"`
}

type ScanSnapshot struct {
	SchemaVersion int64 `json:"schemaVersion"`

	// `scan-2026-08-16T14-32-05`, also the filename stem.
	ID         string `json:"id"`
	StartedAt  string `json:"startedAt"`
	FinishedAt string `json:"finishedAt"`
	DurationMs int64  `json:"durationMs"`
	Hostname   string `json:"hostname"`

	// The config this scan actually ran with, so old snapshots stay self-describing.
	Config     ScanConfig      `json:"config"`
	Totals     ScanTotals      `json:"totals"`
	Extensions []ExtensionStat `json:"extensions"`
	Categories []CategoryStat  `json:"categories"`

	// One node per root, wrapped in a synthetic node when there are several.
	FolderTree FolderNode `json:"folderTree"`

	// Every file at or above `minFileSize`, subject to the topN caps, biggest first.
	Files []FileEntry `json:"files"`

	// Byte-identical file groups, biggest reclaimable weight first.
	DuplicateGroups []DuplicateGroup `json:"duplicateGroups"`

	// Volume figures at scan time, for reconciling the total against reality.
	Volume *VolumeInfo `json:"volume"`

	// Paths from the deletion ledger, checked first and reported here.
	Rechecked []RecheckedPath `json:"rechecked"`

	// Paths that could not be read — usually TCC-protected without Full Disk Access.
	Unscanned []ScanError `json:"unscanned"`
	Warnings  []string    `json:"warnings"`
}

type SnapshotIndexEntry struct {
	ID string `json:"id"`

	// Filename relative to the data directory.
	File          string `json:"file"`
	StartedAt     string `json:"startedAt"`
	DurationMs    int64  `json:"durationMs"`
	TotalBytes    int64  `json:"totalBytes"`
	TotalFiles    int64  `json:"totalFiles"`
	SchemaVersion int64  `json:"schemaVersion"`
}

type SnapshotIndex struct {
	// Newest first.
	Snapshots []SnapshotIndexEntry `json:"snapshots"`
}
